spring.application.name=myanalyst

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/myanalystdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=
spring.jpa.open-in-view=false

rag.server.base-url=${RAG_SERVER_BASE_URL:http://localhost:8000}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.health.redis.enabled=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
